languages:
  JavaScript: true
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 916e9096e28652310c90a83ecdfc1056 #gulpfile.js gulp.src.pipe(eslint.failAfterError());
    - 916e9096e28652310c90a83ecdfc1056 #gulpfile.js gulp.src.pipe(reload());
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
- gulpfile.js
